# Generated by Django 4.0.1 on 2022-02-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='pets_cv/')),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='no', max_length=10)),
                ('neutered', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10)),
                ('CHOICES_SIZE', models.CharField(max_length=100)),
                ('about_me', models.TextField(max_length=250)),
                ('skills', models.TextField(max_length=250)),
                ('achievements', models.TextField(max_length=250)),
                ('things_I_like', models.TextField(max_length=250)),
                ('things_Dont_like', models.TextField(max_length=250)),
                ('desire_compention', models.TextField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
