# Generated by Django 4.0.1 on 2022-02-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='desire_compention',
            new_name='desire_compensation',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='CHOICES_SIZE',
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big'), ('really big', 'Really Big')], default='no', max_length=10),
        ),
    ]
