# Generated by Django 4.0.1 on 2022-02-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_desire_compention_pet_desire_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
