# Generated by Django 4.0.1 on 2022-02-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Pet_CV_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('pet_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='app.pet')),
            ],
        ),
    ]
