# Generated by Django 4.0.1 on 2022-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pet_slug_alter_pet_cv_comments_pet_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(null=True, upload_to='pets_cv/', verbose_name='image'),
        ),
    ]
