# Generated by Django 4.0.1 on 2022-02-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='pets_find_me/')),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='no', max_length=10)),
                ('neutered', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big'), ('really big', 'Really Big')], default='no', max_length=10)),
                ('about_me', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
    ]
