# Generated by Django 4.0.1 on 2022-02-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_findme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findme',
            options={'verbose_name_plural': 'Find Me'},
        ),
        migrations.AddField(
            model_name='findme',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='findme',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='findme',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
