# Generated by Django 4.0.1 on 2022-02-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_findme_options_findme_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find_Me_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('pet_find_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.findme')),
            ],
        ),
    ]
