# Generated by Django 4.0.1 on 2022-03-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_find_me_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find_me_comments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pet_cv_comments',
            name='email',
        ),
        migrations.AddField(
            model_name='find_me_comments',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet_cv_comments',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
